mybatis:
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
spring:
  redis:
    database: 0
    timeout: 3000
    password: zhuge
    #    sentinel:    #哨兵模式
    #      master: mymaster #主服务器所在集群名称
    #      nodes: 192.168.65.60:26379,192.168.65.60:26380,192.168.65.60:26381
    cluster:
      nodes: 192.168.139.128:8001,192.168.139.128:8002,192.168.139.128:8003,192.168.139.128:8004,192.168.139.128:8005,192.168.139.128:8006
    lettuce:
      pool:
        max-idle: 50
        min-idle: 10
        max-active: 100
        max-wait: 1000




